server:
  port: 8008
spring:
  application:
    name: cart-service
  redis:
    host: 47.103.216.75
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: E:\\视频\\rsa\\rsa.pub # 公钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
