server:
  port: 8006
spring:
  application:
    name: sms-service
  redis:
    host: 47.103.216.75
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4Fc9eYA6ARxAN9YeDj48 # 你自己的accessKeyId
    accessKeySecret: QyAJ82NnS3OnNID2QEV5vyPJYyEb5d # 你自己的AccessKeySecret
    signName: SSPU二工大商品交流商 # 签名名称
    verifyCodeTemplate: SMS_177547729 # 模板名称
