server:
  port: 8005
spring:
  redis:
    host: 47.103.216.75
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/sspu
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo
